// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN17AZjNYhTMc4KvsX4h-6Xh1ZPsuWC9s',
    appId: '1:733320819429:web:3af2e49149fe8857769a0c',
    messagingSenderId: '733320819429',
    projectId: 'test-lifeboat',
    authDomain: 'test-lifeboat.firebaseapp.com',
    storageBucket: 'test-lifeboat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBasDGlUb1DluQijzBpI160kQn3i-37C_M',
    appId: '1:733320819429:android:37df05a3cfa6bf9f769a0c',
    messagingSenderId: '733320819429',
    projectId: 'test-lifeboat',
    storageBucket: 'test-lifeboat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvWa29PCaXW486VJVK_d95WJl8XtRGfuQ',
    appId: '1:733320819429:ios:46b4206f422e5061769a0c',
    messagingSenderId: '733320819429',
    projectId: 'test-lifeboat',
    storageBucket: 'test-lifeboat.appspot.com',
    iosBundleId: 'com.example.lifeSaver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvWa29PCaXW486VJVK_d95WJl8XtRGfuQ',
    appId: '1:733320819429:ios:ad1dc6e5afcfe3e4769a0c',
    messagingSenderId: '733320819429',
    projectId: 'test-lifeboat',
    storageBucket: 'test-lifeboat.appspot.com',
    iosBundleId: 'com.example.lifeSaver.RunnerTests',
  );
}
