// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpewqGYYeFQ1_pPF6Td1aapg1htY_iFA8',
    appId: '1:152549097696:web:017b6592a3c2e086d91085',
    messagingSenderId: '152549097696',
    projectId: 'lifesaver-3000',
    authDomain: 'lifesaver-3000.firebaseapp.com',
    storageBucket: 'lifesaver-3000.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5wLM4XHkklh9qkp8RcR_ncL1k_0UW92U',
    appId: '1:152549097696:android:6e7f7e53ed8ae8c3d91085',
    messagingSenderId: '152549097696',
    projectId: 'lifesaver-3000',
    storageBucket: 'lifesaver-3000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaFSy7ceezKvmqNwfZJnxwuk-36jLSJug',
    appId: '1:152549097696:ios:aacc7c5742673970d91085',
    messagingSenderId: '152549097696',
    projectId: 'lifesaver-3000',
    storageBucket: 'lifesaver-3000.appspot.com',
    iosBundleId: 'com.example.lifeSaver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaFSy7ceezKvmqNwfZJnxwuk-36jLSJug',
    appId: '1:152549097696:ios:9a47b1cb2f3ffab9d91085',
    messagingSenderId: '152549097696',
    projectId: 'lifesaver-3000',
    storageBucket: 'lifesaver-3000.appspot.com',
    iosBundleId: 'com.example.lifeSaver.RunnerTests',
  );
}
